### ISSUE TITLE
Unable to run dreamGPT

### ISSUE THREAD

**Issue by codeshoel** [DivergentAI/dreamGPT#6]
Hi team, I cloned and followed the README instruction on setting up **dreamGPT**, but currently got an error when I tried using the cmd run install poetry and got **"bash: run: command not found"**. Please let me know if I am missing something in the setup process.

**Step taken to get script running on my local machine:**
1. cloned the repository
2. install required Python packages as required in the README using **pip install -r requirements.txt**
3. Created a Pinecone account and generated an API_KEY
4. Added my Pinecone API_KEY to the .env file

**Comment by sachaa** [comment]
Thanks a lot for trying out dreamGPT. Based on your description, it sounds like you might be misinterpreting the instructions. When the README says to "run" a command, it doesn't mean to type "run" before the command.

In your case, if you're trying to install poetry, the command would just be `poetry install`, not `run poetry install`.

Would love to hear your feedback once you try it!
